### ISSUE TITLE
Minor mistake in readme

### ISSUE THREAD

**Issue by golles** [matijse/eufy-ha-mqtt-bridge#14]
json_attribute_topic should be json_attributes_topic.

I found this out because I thought the sensors were not discovered, then I realized they are not detected as devices but as entities.

Maybe also consider a docker-compose example:
```
  eufy-bridge:
    container_name: eufy-bridge
    image: matijse/eufy-ha-mqtt-bridge
    restart: unless-stopped
    volumes:
      - /path/to/local/data/folder:/app/data
```
