### ISSUE TITLE
camera.deurbel_last_event doesn't have a picture

### ISSUE THREAD

**Issue by golles** [matijse/eufy-ha-mqtt-bridge#23]
I noticed that most of the time the camera entity has no valid picture

```yaml
access_token: dd1b40db1446780f051d744efd2c4b7628f3110bblablabla
friendly_name: Deurbel - Last event
entity_picture: >-
  /api/camera_proxy/camera.deurbel_last_event?token=dd1b40db1446780f051d744efd2c4b7628f3110bblablabla
supported_features: 0
```

If I open the entity_picture url in the browser I get `500: Internal Server Error`

error and exceptions log files are empty, combined log only has successful entries.

Mqtt explorer is showing an entry for the camera, but it doesn't contain an image.

```json
{"name":"Deurbel - Last event","topic":"homeassistant/camera/eufy/T8210P00bla_thumbnail","unique_id":"T8210P00bla_thumbnail"}
```
